### ISSUE TITLE
working with interactor ( server ) 

### ISSUE THREAD

**Issue by omert742** [Yalantis/kotlin-mvp-example#1]
when i am making a call to the server i do it in sepated class call "intercator " when i get response , 
should the interaction interact directly to the viewModel for let the activity know the action success/failed or should it first run throw the presenter model and only from there move to the viewModel ?

**Comment by PenzK** [comment]
It depends on what architecture approach you have selected MVVM, MVP or MVC or Clean Architecture. In our case we have repository which interacts with presenter and then present can tell to view what to show
