### ISSUE TITLE
Moshi instead of Gson

### ISSUE THREAD

**Issue by sylflo** [Yalantis/kotlin-mvp-example#2]
First thank you for you work.
I'm wondering why choosing Gson instead of Moshi ? Since Moshi has some optimizations that Gson does not have.
https://stackoverflow.com/questions/43577623/moshi-vs-gson-in-android

**Comment by PenzK** [comment]
Thanks, we will check it. You are welcome with pull requests

**Comment by PenzK** [comment]
We decided to give it a try, now in develop branch
