### ISSUE TITLE
Snackbar.LENGTH_LONG in place of Toast.LENGTH_LONG in BaseMvpActivity.kt

### ISSUE THREAD

**Issue by PuniCharana** [Yalantis/kotlin-mvp-example#4]
Is it okay to mix up Snackbar.LENGTH_LONG & Toast.LENGTH_LONG ? The app is getting compiled but Android Studio is giving red line with a message `Must be one of:Toast.LENGTH_LONG  , Snackbar.LENGTH_LONG found.`

https://github.com/Yalantis/kotlin-mvp-example/blob/develop/app/src/main/java/client/yalantis/com/githubclient/mvp/BaseMvpActivity.kt

**Comment by PenzK** [comment]
Fixed
